# Add an object to the object database of the node.

# Object name
string                  name
# ???
geometry_msgs/Point     anchor
# Image
sensor_msgs/Image       image
---
# Return status
#FIXME: is it needed?
int8                    status
